name: Build Windows Manual

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build do RustDesk
        run: |
          cargo build --release
        # Removemos o --features inline e o vcpkg para evitar conflitos de ambiente
        
      - name: Upload do Executável
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-exe
          path: target/release/rustdesk.exe
